---
#------------------------------------------------------------------------------
# Start tasks 
#------------------------------------------------------------------------------


  - name: OUTPUT LIST OF DEPLOYED BIG-IPS
    debug:
      msg: "{{ bigip_mgmt_ips }}"

#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...