---
#------------------------------------------------------------------------------
# Ansible Playbook to Delete Demo Environment
#------------------------------------------------------------------------------
- name: PROVISION VPC SUBNETS & F5 INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ ec2_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ ec2_secret_key }}"
    AWS_REGION: "{{ aws_region }}"

#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------
  
  vars_files:
    - ../../../creds/creds.yaml
    - ./vars/vars.yaml


  tasks:
    - include_tasks: ./tasks/delete.yaml

...