---
#------------------------------------------------------------------------------
# Playbook to CREATE AWS demo environment..  Requires Ansible 2.8.1
#------------------------------------------------------------------------------

- name: PROVISION VPC SUBNETS & F5 INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ ec2_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ ec2_secret_key }}"
    AWS_REGION: "{{ aws_region }}"

    

#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------
  
  # You need to create a file named aws_creds.yaml (update path below) with the 
  # following variables:
  #
  #  ec2_access_key: "--your-key-here--"
  #  ec2_secret_key: "--your-secret-here--"
  #
  vars_files:
    - ../../../creds/aws_creds.yaml
    - ../../../creds/aws_big_creds.yaml
    - ./vars.yaml

#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------

  tasks:

  - include_tasks: aws-create-vpc-tasks.yaml
  - include_tasks: aws-create-cft-tasks.yaml
    loop: "{{ cft_stack_name_list }}"
    loop_control:
      loop_var: stack_name
  - include_tasks: aws-create-outputs.yaml

# Use/uncomment the loop control below to create single devices in multiple regions.
#
#  - include_tasks: aws-create-tasks.yaml
#    loop:
#        - eu-west-1
#        - eu-west-2
#        - eu-central-1
#        - us-east-1
#        - us-east-2
#        - us-west-2
#        
#    loop_control:
#      loop_var: aws_region


#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...