---
#------------------------------------------------------------------------------
# Ansible Playbook to Delete Demo Environment
#------------------------------------------------------------------------------
- name: PROVISION VPC SUBNETS & F5 INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_SESSION_TOKEN: "{{ aws_session_token }}"
    
    AWS_REGION: "{{ aws_region }}"

#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------
  
  # You need to create a file named aws_creds.yaml (update path below) with the following variables:
  #
  #  ec2_access_key: "--your-key-here--"
  #  ec2_secret_key: "--your-secret-here--"
  #
  vars_files:
    - ../../../creds/aws_creds.yaml
    - ./vars.yaml
  
#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Start Tasks
#------------------------------------------------------------------------------

  tasks:

# Use/uncomment the loop control below to create single devices in multiple regions.
#
#  - include_tasks: aws-delete-tasks.yaml
#    loop:
#        - eu-west-1
#        - eu-west-2
#        - eu-central-1
#        - us-east-1
#        - us-east-2
#        - us-west-2
#        
#    loop_control:
#      loop_var: aws_region


# Use/uncomment the loop control below to create single devices in same region.
#
  - include_tasks: aws-delete-cft-tasks.yaml
    loop: "{{ cft_stack_name_list }}"
    loop_control:
      loop_var: stack_name

  - include_tasks: aws-delete-vpc-tasks.yaml

#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...