---
#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------

  - name: DEPLOY AWS CFT TO CREATE BIG-IP HA PAIR
    cloudformation:
      stack_name: "{{ stack_name }}"
      state: present
      region: "{{ aws_region }}"
      disable_rollback: true
      template_url: "https://s3.amazonaws.com/f5-cft/f5-existing-stack-same-az-cluster-payg-2nic-bigip.template"
      template_parameters:
        group:  "f5group"
        declarationUrl:  "none"
        Vpc: "{{ vpc_id }}"
        managementSubnetAz1:  "{{ vpc_subnet_ids.mgmt_a }}"
        subnet1Az1:  "{{ vpc_subnet_ids.traffic_a }}"
        restrictedSrcAddress: "0.0.0.0/0"
        restrictedSrcAddressApp: "0.0.0.0/0"
        sshKey:  "{{ sshKey }}"
        environment:  "Demo"
        application:  "f5app"
        customImageId:  "OPTIONAL"
        imageName:  "Best25Mbps"
        ntpServer:  "0.pool.ntp.org"
        costcenter:  "SALES EMEA-UK 4261"
        owner:  "{{ uk_se_name }}"
        timezone:  "UTC"
        instanceType:  "m5.xlarge"
        allowUsageAnalytics:  "Yes"
      tags:
        automated: "{{ automation_tool }}"
        stack: "{{ stack_name }}"
        UK-SE: "{{ uk_se_name }}"
    register: result 
    until: result is not failed
    retries: 5


  - name: GATHER FACTS FROM AWS CFT OUTPUT - NEED BIG-IP PUBLIC IPS 
    cloudformation_facts:
      stack_name: "{{ stack_name }}"
      stack_resources: true
    register: my_stack


  - name: WAIT FOR SSH ACCESS - CHECK EVERY 10 (MAX 600)
    wait_for:
      host: "{{ item }}"
      port: 22
      delay: 0
      sleep: 10
      connect_timeout: 5
      timeout: 600
      msg: "Failed to detect SSH port open"
    loop:
      - "{{ my_stack.ansible_facts.cloudformation[stack_name].stack_outputs.Bigip1ManagementEipAddress }}"
      - "{{ my_stack.ansible_facts.cloudformation[stack_name].stack_outputs.Bigip2ManagementEipAddress }}"


  - name: CHECK FOR READY SIGNAL FILE - CHECK EVERY 10 (MAX 600)
    bigip_command:
      commands:
        - "run /util bash -c 'test -f /tmp/f5-cloud-libs-signals/ADMIN_CREATED && echo ADMIN_CREATED'"
      wait_for:
        - result contains ADMIN_CREATED
      interval: 10
      retries: 60
      provider:
        server: "{{ item }}"
        user: "{{ bigip_user }}"
        password: "{{ bigip_pass }}"
        transport: cli
        ssh_keyfile: "{{ ssh_key_file_path }}"
        validate_certs: no
    register: ssh_output
    delegate_to: localhost
    loop:
      - "{{ my_stack.ansible_facts.cloudformation[stack_name].stack_outputs.Bigip1ManagementEipAddress }}"
      - "{{ my_stack.ansible_facts.cloudformation[stack_name].stack_outputs.Bigip2ManagementEipAddress }}"
    until: ssh_output is not failed
    retries: 5
     

  - name: SSH TO BIG-IPS AND ENABLE PASSWORD AUTH
    bigip_command:
      commands:
        - modify auth user "{{ bigip_user }}" password "{{ bigip_pass }}" 
        - save sys config
      wait_for:
        - result[1] contains done
      provider:
        user: "{{ bigip_user }}"
        password: "{{ bigip_pass }}"
        server: "{{ item }}"
        transport: cli
        ssh_keyfile: "{{ ssh_key_file_path }}"
        timeout: 60
        validate_certs: no
    register: ssh_output
    delegate_to: localhost
    loop:
      - "{{ my_stack.ansible_facts.cloudformation[stack_name].stack_outputs.Bigip1ManagementEipAddress }}"
      - "{{ my_stack.ansible_facts.cloudformation[stack_name].stack_outputs.Bigip2ManagementEipAddress }}"
    until: ssh_output is not failed
    retries: 5

#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...