---
#------------------------------------------------------------------------------
# Ansible Playbook to Delete Demo Environment
#------------------------------------------------------------------------------

- name: DELETE VPC SUBNETS & F5 INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ ec2_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ ec2_secret_key }}"
    AWS_REGION: "{{ aws_region }}"

#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------
  
  # You need to create a file named aws_creds.yaml (update path below) with the following variables:
  #
  #  ec2_access_key: "--your-key-here--"
  #  ec2_secret_key: "--your-secret-here--"
  #
  vars_files:
    - ../../creds/aws_creds.yaml
    - ./vars/vars.yaml
  
#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Start Tasks
#------------------------------------------------------------------------------

  tasks:

  - include_tasks: ./tasks/tasks-11-aws-delete-cft.yaml


#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...